"""
Django settings for otp_project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-(!!gf$u%(ko!7w@5dz_2n!o2z3^#fbw+*q37egju_rsf-w^sb-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'users',
    'django_otp',
    'django_otp.plugins.otp_totp',
    # 'registration',
    # 'api',
    #
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "otp_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "otp_project.wsgi.application"

AUTH_USER_MODEL = 'users.User'
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# MAILTRAP_API_KEY=os.getenv('MAILTRAP_API_KEY')
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'shawazimagezi@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'ehwu vxhz ntws ttqm'  # Your email password or app password
DEFAULT_FROM_EMAIL = 'shawazimagezi@gmail.com'


# AUTH_USER_MODEL = 'registration.CustomUser'
# AUTH_USER_MODEL = 'registration.CustomUser'

AUTH_USER_MODEL = 'users.User'


# SMSLEOPARD_ACCOUNT_ID = 'your_account_id'
# SMSLEOPARD_ACCOUNT_SECRET = 'your_account_secret'
# SMSLEOPARD_SENDER_ID = 'your_sender_id'


# SMSLEOPARD_API_KEY = 'your_smsleopard_api_key'
# SMSLEOPARD_API_SECRET = 'your_smsleopard_api_secret'
# SMSLEOPARD_SENDER_NAME = 'YourCompany'

SMSLEOPARD_API_KEY: 'OqupIVE5kqicYArG2wEY'
SMSLEOPARD_API_SECRET: 'qTs22s0q16e1KE8B2RCCglG8pLkbrGEegTh1KErl'
# Access token: T3F1cElWRTVrcWljWUFyRzJ3RVk6cVRzMjJzMHExNmUxS0U4QjJSQ0NnbEc4cExrYnJHRWVnVGgxS0VybA==
SMSLEOPARD_SENDER_NAME: 'Shawazi_Magezi'
# Environment: production